### ISSUE TITLE
Parse error: syntax error, unexpected '?' in C:\wamp64\www\bugtracking-master\index.php on line 8

### ISSUE THREAD

**Issue by Shubhamshrimali** [samirank/bugtracking#1]
: , :\wamp64\www\-master\index.php on line 8
--

<?php $err=$_SESSION['err']??null;
unset($_SESSION['err']);
if($err==1){
  $err="<br><span style='color: red; padding: 10px'>Login failed</span>";
} ?>

**Comment by samirank** [comment]
'??' is a null coalesce operator supported only in PHP version 7 make sure you are using a supported version of PHP.
http://php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op
